template: |
  ## SHORT OVERVIEW
  - Bug FixesASD

  ## NEW FEATURES
  - EXPEDITION reroll currency display now depends on market price/stack size. They are now part of the generic currency tierlist

  ## CRAFTING
  - Nerfed synthesized item highlight a bit
  - Adjusted the prefered synth/fractured item classes
  - Any identified uncorrupted amulet with the +1 to all skills mod is now highlighted

  ## TIERING
  - UNIQUE 5 links highlight nerfed. They no longer produce a T2 sound.
  - INFLUENCED tiering has been made much more precise ( DETAILS: When tiering itemlevel 80-84 influenced items, the algorithm checks if the economy data for the same base/influence at ilvl 85/86 is at least as high and also matches the threshhold. This prevents random misspriced items and crafted items to be overtiered and highlighted as expensive for no reason. I've been observing this adjustment over the past month and it seems to cause overwhelmingly positive effects )
  - DIVINATION CARD tiering for later league stages has been improved. ( DETAILS: Many more low value/popularity cards will now drop into lower tiers in later phases of the league. This only affects low value cards that mostly grant single uniques. Cards with random outcomes are mostly unaffected. )
  - CLUSTER JEWEL tiering during the first 3-4 days of new leagues will be using the same tiering as at the end of the last league. This is not perfect, but likely better than not doing anything or accepting highly noisy early league data.
  - FRAGMENT-lures are now economy-tiered, but are disallowed from being hidden as a safeguard
  - Did a lot of general clean up to the source code of the tiering algorithm. Improved a few niches and calculations.

  ------

  ## CREDITS:

  Release By: NeverSink

  [![Follow me on Twitter](https://img.shields.io/badge/twitter-grey.svg?style=for-the-badge&logo=twitter)](https://twitter.com/NeverSinkDev) [![FilterBlade Discord](https://img.shields.io/badge/discord-grey.svg?style=for-the-badge&logo=discord)](https://discord.gg/mye6xhF) [![Watch FB Dev on Twitch](https://img.shields.io/badge/twitch-grey.svg?style=for-the-badge&logo=twitch)](https://twitch.tv/neversink) [![Support development on Patreon](https://img.shields.io/badge/patreon-grey.svg?style=for-the-badge&logo=patreon)](https://www.patreon.com/Neversink)