template: |
  *All updates are also available through [FilterBlade](https://www.filterblade.xyz) and on the [PoE filter ladder](https://www.pathofexile.com/item-filter/ladder/follower). Major thanks to all patreon supporters to help us fund the continuous development. [Patreon](https://www.patreon.com/Neversink) supporters also receive a Patreon-exclusive [Filter-Auto-Updater](https://youtu.be/i8RJx0s0zsA).*
  
  ## SHORT OVERVIEW:
  
  - Improved the treatment for the monochrome card
  - Unique tinctures are now tiered correctly using economy data
  - Added some missing old wands to the tiering that changed their base, such as Twyzel
  - Reduced the large heist coin pile size from 500 to 400 to better account for locker contents
  - Added some selected level 3 heist gear pieces to the T2 heist items to help guff out (and prevent level 3 items from costing half a divine)
  - Hivebrain gland is now economy tiered (but not allowed to drop below T3)
  - Other minor changes
  
  ------

  Developed by NeverSink

  [![Follow me on Twitter](https://img.shields.io/badge/twitter-grey.svg?style=for-the-badge&logo=twitter)](https://twitter.com/NeverSinkDev) [![FilterBlade Discord](https://img.shields.io/badge/discord-grey.svg?style=for-the-badge&logo=discord)](https://discord.gg/mye6xhF) [![Watch FB Dev on Twitch](https://img.shields.io/badge/twitch-grey.svg?style=for-the-badge&logo=twitch)](https://twitch.tv/neversink) [![Support development on Patreon](https://img.shields.io/badge/patreon-grey.svg?style=for-the-badge&logo=patreon)](https://www.patreon.com/Neversink)
