template: |
  *All updates are also available through [FilterBlade](www.filterblade.xyz) and on the [PoE filter ladder](https://www.pathofexile.com/item-filter/ladder/follower). Major thanks to all patreon supports to help us fund the continious development. [Patreon](https://www.patreon.com/Neversink) supporters also receive a Patreon-exclusive [Filter-Auto-Updater](https://youtu.be/i8RJx0s0zsA).*
  
  ## SHORT OVERVIEW
  Say hi to your Sentinel! The filter incorporates all of the new league features and a bunch of precedural upgrades!
  
  ## NEW LEAGUE FEATURES
  - Added all new divination cards
  - Added the reworked divination cards
  - Added unique adjustments where necessary to minimize chances of hiding new uniques
  - Added a simple section to highlight sentinels. For now I'm keeping it simple, but I'll release a more sophisticated version, once we know more about the league. All sentinels currently have a purplish background and an easily distinguishable text color that represents rarity. They're shown on the minimap with the teal "pentagon" icon
  - Aded all new currencies.
  - Removed all the old archnemesis sections
  
  ## CRAFTING AND RARES
  - Reviewed all higlighted rares in all tiers. Improved my algorithms and tooling to make the selection more accurate and to make better and more informed decisions
  - Reviewed crafting bases as well
  - Adjusted the highlight level and selection of synthesised and factured items
  - With the introduction of eldritch influences certain fractured and synthesised items have gained or lost in price and popularity. Generally speaking fractured boots/gloves/shields/helmets have become beter, while their synthesised counterparts lost in power
  - Any identified uncorrupted amulet with the +1 to all skills mod is now highlighted
  - Quality based flask rules have all been reduced in their priority and are disabled in lower strictnesses
  - Very slightly adjusted the appearance of T2, T3 and T4 rares
  
  ## TIERING
  - All tierlists have been adjusted to better reflect the ingame economy
  - EXPEDITION reroll currencies are now economy-tiered
  - Their display depends on the current market price and on the dropped stack. The algoritms currently has special safeguards in place to prevent them from ever dropping below alchemy tier.
  - UNIQUE 5 links highlight nerfed. They no longer produce a T2 sound.
  - This has more often than not resulted in in disapointment.
  - INFLUENCED tiering has been made much more precise
  - When tiering itemlevel 80-84 influenced items, the algorithm checks if the economy data for the same base/influence at ilvl 85/86 is at least as high and also matches the threshhold. This prevents random misspriced items and crafted items to be overtiered and highlighted as expensive for no reason. I've been observing this adjustment over the past month and it seems to cause overwhelmingly positive effects by reducing the chances of accidental bamboozels.
  - DIVINATION CARD tiering for later league stages has been improved.
  - Many low value/popularity cards will now drop into lower tiers in later phases of the league (based on price). This only affects low value cards that mostly grant single uniques. Cards with random outcomes are mostly unaffected.
  - CLUSTER JEWEL tiering during the first 3-4 days of new leagues will be using the same tiering as at the end of the last league.
  - This is not perfect, but likely better than not doing anything or accepting highly noisy early league data. I have a better algorithm in mind, but that one will take more time to develop
  - Cluster jewels also receive a slight artifical bias at the start of the league
  - FRAGMENT-lures are now economy-tiered, but are disallowed from being hidden as a safeguard
  - Did a lot of general clean up to the source code of the tiering algorithm. Improved a few niches and calculations
  - Improved Oil tiering, it's a bit less strict for lower tier oils and moves certain oils higher at the start of the league
  - Improved the collection of early league uniques (with twitch chats support!)
  - Elderslayer fragments are now tierable by the economy
  - The basic maven invitation is now anchored to T3 and won't change it's tier
  - Abyssal incubators now have more priority if they have a high item level
  
  ## LEVELING
  - The general weapon progression (not the custom one defined in filterblade) requires 3+ sockets on items. This will decrease the amount of clutter, while giving the player still enough items to through an essence or an alch on.
  - Adjusted some keylevels for leveling progressions.
  - Random 3-socket gear will be shown until level 9, instead of 8
  - Internal act 1 level changed from 15 to 16
  - Added two-stone ring highlight to earlier sections
  
  ## MISC
  - T2 heist gear is now hidden on uber-strict instead of uber-plus-strict
  - Changed the background on identified mod items from dark blue to dark purple to prevent confusion with the sentinel color-space
  - Adjusted chancing bases ("Heavy Belt" "Leather Belt" "Elegant Round Shield" "Ezomyte Dagger" "Champion Kite Shield" "Fiend Dagger" "Prophecy Wand")
  
  ## ARCHITECTURE
  - The filter now consistently considers ItemLevels or AreaLevels of 68 or higher as endgame ( >= 68 operator ). FilterBlade rules and descriptions have been adjusted as well.
  - The filter now consistently considers ItemLevels or AreaLevels 67 or below as leveling ( <= 67 operator ). FilterBlade rules and descriptions have been adjusted as well.
  
  ## FilterBlade and technical improvements
  - IMPROVED BASETYPE MATRIX: These have become a central tool of FilterBlade and we've invested effort to enhance these with new options
  - Matrixes are now available for many more sections, such as rare jewelery, synthesised, fractured bases and others
  - Their display has been optimized and now better presents data on one sight
  - The matrix for endgame rares now no longer handles the T3 by droplevel, this allows you to finetune T3 rares much better
  - Improved the general visualization strategy
  - You now have the option to show all items at once grouped by tier. This is very useful if you want to remove specific items from a specific tier
  - You can now rightclick to set all visible items in the matrix to a certain tier
  - You can now rightclick to copy and paste the visible tiering. Yes you can finally sync your rares with your crafting stuff etc.
  - ADDED +1 SKILL RECIPE SECTION: 5 new (optional) gem sections to show specific quality gems for specific +1to all gems recipes. These can be enabled in filterblade easily
  - ADDED GLOBAL STYLE EDITS SECTION: A new tool in the style section. It enables global edits across the whole filter.
  - It allows you to remove all backgrounds, borders (etc), scale font sizes, minimize and maximize item fonts, edit sound options and many more.
  - It also edits 'the base filter' and doesn't cause your customizer to become "fully blue"
  - It's great for large style modifications of the filter
  - Significantly improved the filter deployment and release pipeline. It now has a dozen of utiltiy steps to ensure version number consistency, better changelogs, better github releases, auto-refreshes my token to prevent the system requiring manual cranking every month etc.
  - Reworked the attached changelog. It's now stored in markdown format and is much more structured.
  - Added ad-related cookie consent UI and improved privacy policy. We don't collect any personal data on FilterBlade (or want it), but we're legally bound to show the UI, since ads might do that.
  
  ## FilterBlade breaking changes
  Either PoE or the architectue behind the following filterblade sections has been adjusted massively and you will have to redo your changes in FilterBlade in the following sections:
  - Rare Tiering - T3 (so that you can move individual bases now and not just adjust droplevels)
  - Archnemesis mods (being removed)
  - Expedition rerolls (being merged into normal currencies)
  
  ------

  Developed by NeverSink

  [![Follow me on Twitter](https://img.shields.io/badge/twitter-grey.svg?style=for-the-badge&logo=twitter)](https://twitter.com/NeverSinkDev) [![FilterBlade Discord](https://img.shields.io/badge/discord-grey.svg?style=for-the-badge&logo=discord)](https://discord.gg/mye6xhF) [![Watch FB Dev on Twitch](https://img.shields.io/badge/twitch-grey.svg?style=for-the-badge&logo=twitch)](https://twitch.tv/neversink) [![Support development on Patreon](https://img.shields.io/badge/patreon-grey.svg?style=for-the-badge&logo=patreon)](https://www.patreon.com/Neversink)