template: |
  *All updates are also available through [FilterBlade](https://www.filterblade.xyz) and on the [PoE filter ladder](https://www.pathofexile.com/item-filter/ladder/follower). Major thanks to all patreon supporters to help us fund the continuous development. [Patreon](https://www.patreon.com/Neversink) supporters also receive a Patreon-exclusive [Filter-Auto-Updater](https://youtu.be/i8RJx0s0zsA).*
  
  ## SHORT OVERVIEW:
  
  Idols dropping in the Legacy of Phrecia league have been added to the filter!
  
  ## NEW FEATURES:
  - Added a rule for every of 6 idol types - Magic version
  - Added a rule for every of 6 idol types - Rare version
  - Added a rule for unique idols dropping
  - Added a safety rule for normal idols dropping. Just in case.
  
  ## IMPORTANT TECHNICAL CHANGES:
  
  I've massively improved my filter-generation tooling, this enables some new capabilities!
  
  - I can now support even-specific filters: The legacy of phrecia - of Phrecia Event now has full economy support! FilterBlade will have 2 legacy of phrecia dedicated versions of the filter for the duration of the event. The stable filter supports both legacy/main league event gameplay.
  - Added a new system to create whitelist/blacklist tiers for individual items during a specific league state. This helps with making better and safer tiering decisions at the start of new leagues!
  
  ------

  Developed by NeverSink

  [![Follow me on Twitter](https://img.shields.io/badge/twitter-grey.svg?style=for-the-badge&logo=twitter)](https://twitter.com/NeverSinkDev) [![FilterBlade Discord](https://img.shields.io/badge/discord-grey.svg?style=for-the-badge&logo=discord)](https://discord.gg/mye6xhF) [![Watch FB Dev on Twitch](https://img.shields.io/badge/twitch-grey.svg?style=for-the-badge&logo=twitch)](https://twitch.tv/neversink) [![Support development on Patreon](https://img.shields.io/badge/patreon-grey.svg?style=for-the-badge&logo=patreon)](https://www.patreon.com/Neversink)
