template: |
  *All updates are also available through [FilterBlade](https://www.filterblade.xyz) and on the [PoE filter ladder](https://www.pathofexile.com/item-filter/ladder/follower). Major thanks to all patreon supporters to help us fund the continuous development. [Patreon](https://www.patreon.com/Neversink) supporters also receive a Patreon-exclusive [Filter-Auto-Updater](https://youtu.be/i8RJx0s0zsA).*
  
  ## UNIQUE TIERING
  - Removed a bunch of aspects from no-longer-dropping uniques. This will lead to a bunch of uniques that were previously landingg in the "non-drop-category" to land into the hideable category (thanks @mellontoss)
  - Removed around 10 basetypes from the unique tierlist that no longer drops (usually due to their basetypes being changed). Has no ingame effect, but reduces file size and helps filterblade clarity.
  - Marked the alt-art asphyxia's wrath with non-drop. (thanks @mellontoss)
  
  ## UNIQUE JEWEL TIERING
  - Added minimal unique jewel tiering where possible. In the case of most jewels this does not work as too many jewels share the same base. However, some jewels such as abyss jewels are now economy-tiered.
  - Rational doctrine drops are now highlighted as T1 (using the fact that they're the only synthesised jewel)
  
  ## DIVINATION TIERING
  - Cleaned and improved the aspects (meta-information) of the divination cards. This should lead to some improved tiering in some niche cases.
  
  ## MISC CHANGES
  - Increased the stack size requirement on all simulacrum splinters to create high tier sounds/highlights.
  
  ------

  Developed by NeverSink

  [![Follow me on Twitter](https://img.shields.io/badge/twitter-grey.svg?style=for-the-badge&logo=twitter)](https://twitter.com/NeverSinkDev) [![FilterBlade Discord](https://img.shields.io/badge/discord-grey.svg?style=for-the-badge&logo=discord)](https://discord.gg/mye6xhF) [![Watch FB Dev on Twitch](https://img.shields.io/badge/twitch-grey.svg?style=for-the-badge&logo=twitch)](https://twitch.tv/neversink) [![Support development on Patreon](https://img.shields.io/badge/patreon-grey.svg?style=for-the-badge&logo=patreon)](https://www.patreon.com/Neversink)
