template: |
  *All updates are also available through [FilterBlade](https://www.filterblade.xyz) and on the [PoE filter ladder](https://www.pathofexile.com/item-filter/ladder/follower). Major thanks to all patreon supporters to help us fund the continuous development. [Patreon](https://www.patreon.com/Neversink) supporters also receive a Patreon-exclusive [Filter-Auto-Updater](https://youtu.be/i8RJx0s0zsA).*
  
  ## SHORT OVERVIEW
  
  Necropolis has been integrated into the filter! On top of all of the necessary changes this update improves upon the existing strictness progression, revamps fractured bases, adds several new rules.
  
  ## IMPORTANT-TO-KNOW CHANGES:
  - IMPORTANT: The bossdrop-unique-tier is now hidden on uber-plus strict! If you do some bossing on this strictness be sure to show hidden items with ALT.
  - IMPORTANT: Low tier-base or corrupted non-unique six-links are hidden on uber-plus strict
  - IMPORTANT: Unidentified rare corrupted items with 0 corrupted mods are now hidden. This excludes leveling, jewellery, high linked/socketed gear and 'exotic' cases (such as runic items and all kind of exceptions)
  
  ## NECROPOLIS LEAGUE RELATED CHANGES
  
  - Added a low priority rule designed to highlight all items created in the necropolis (rare identified equip pieces of arealevel 1 items of itemlevel larger than 4)
  - Added new scarabs and some basic tiering
  - Added T17 maps
  - Added allflames (and some very basic tiering)
  - Added the new heist belt
  - Migrated the Veiled Chaos Orb
  - Added section to highlight items with necropolis craft mods
  - Removed all obsolete items (invitations, sextants, compasses)
  - Removed the beyond map rule
  - All tierlists have been adjusted:
  - This currently includes the following tierlists: Uniques, Divination Cards, Fragments (incl. splinters), Currency (incl. stacked currency and shards), Scarabs, Unique Maps, Fossils, Incubators, Oils, Vials, Delirium Orbs, Influenced Items, Expensive Atlas Bases, Cluster Jewels, Breachstones, Replicas, Omen, Tattoos and Gems.
  
  ## MAP RELATED CHANGES:
  - Added a new rule to highlight the T17 maps
  - Added a new rule to highlight maps with corrupted implicits
  - Removed the rule highlighting maps with the beyond mod (becuase the mod is gone)
  
  ## NEW FEATURES:
  - Unidentified rare corrupted items with 0 corrupted mods are now hidden. This excludes leveling, jewellery, high linked/socketed gear and 'exotic' cases (such as runic items and all kind of exceptions)
  - Added a new tier to the unique tierlist: high-multi-base uniques. This tier will contain uniques that have a chance to have highly expensive WORLDDROPS (important: NOT bosses!), such as Heavy Belts and Leather Belts. The minimum value requirement is 5x T1 price threshold. The purpose is to make unique tiering easier. The rule has the same appearance, but uses purple map colors and beams.
  - Added a new rare decorator rule that gives 4linked rares a special border. This is useful early on in the league as these rares tend to sell much better. Higher strictnesses that hide rares won't be affected by it.
  - Added a rule to detect fractured veiled items. This does not guarantuee that the fractured mod is the veil. If both align - you get a fractured veiled item - something potentially very valuable.
  - Added detection of identified bone rings with a promising combinations of mods
  - The reworked 'wraithlord' helmet unique with 4 abyss sockets received a special rule that detects it (by the abyss sockets)
  - Added a new optional rule to highlight magic generic jewels with at least 1 corrupted modifier. These jewels are potentially useful for the adorned unique. These jewels will likely drop unidentified and most results will be not too useful. The rule is disabled on very strict. Experienced and interested players can reenable it of course.
  - Reworked and refined the endgame flasks rules quite a bit, some old rules have been removed and a few exceptions have been revamped. Among others I've added a new rule to highlight 30% qual corrupted endgame magic flasks.
  - Added a new rule for Forbidden Tomes of ILVL 83. This is pretty much just to simplify filterblade editing.
  
  ## HIGHLIGHT AND STYLE CHANGES:
  
  - Strengthened the highlight of all utility-flasks
  - Reworked the appearance of six-links. High tier six-links look like low tier six links before (crimson background, white accents), while low tier sixlinks use a new appearance.
  - Introduced a new appearance into the filter: a turquoise looking tierlist - this is currently used only by allflames and is intended to be used as a tierlist for new league items.
  
  ## STRICTNESS ADJUSTMENTS:
  
  There are a lot of rules in the filter that have lost most of their pratical relevance for normal gameplay over the years. In this update, I disabled a whole bunch of these rules. The filterblade ruthless filter mode will be adjusted to reanable those.
  
  - The bossdrop-unique-tier is now hidden on uber-plus strict! If you do some bossing on this strictness be sure to show hidden items with ALT.
  - All chisel recipe rules are now disabled.
  - Disabled some endgame low quality flasks rules (the flasks will still be highlighted, if they're useful, but the quality itself won't trigger a highlight)
  - Low Level T2 crafting items are now disabled
  - 84+ Level T3 crafting items are now disabled
  - 86+ Level T3 crafting items are now hidden on semi-strict
  - Increased the strictness of talisman filtering
  - Cleaned up 'Perfection' bases (ilvl86 bases with perfect implicit defense roll, otherwise only changable with Sacred Orbs) to only have 2 tiers and recommend betters items. The second tier is disabled by default. The first tier is disabled on uber-strict.
  - Poor non-unique 6links (corrupted, low level or not one of the higher bases) are now disabled on Uber-Plus-Strict.
  - T5, T5currency, T4, T4currency cards are now filtered stricter.
  - This is not a comprehensive list, there are more minor strictness adjustments
  
  ## IDENTIFIED MOD RULES:
  - ES recharge rate and faster recharge start has been almost universally removed from the list of desirable mods.
  - Identified gloves: properly split ES and life based gloves
  - Identified boots: decreased the importance of defenses
  - Identified quivers: now require 2 'core mods' instead of one.
  - Identified shields: removed a lot of the less valuable mods like %physical damage reduction and added new useful combinations
  - Added a strictness gradient to the identified mod detection. Most identified mod rules are now disabled on uber-plus strict. Some rules are disabled on uber-strict (such as identified body armor rules). You can of course enable combinations you are interested in on FilterBlade.
  
  ## MISC CHANGES:
  - Hinekora's Lock has been moved into the currency tier
  - The reworked divination cards have been retiered
  - Fixed a rare bug that would cause some cluster/abyss jewels to be highlighted, despite being hidden on filterblade
  - Top tier life and mana flasks (no quality) are now shown up to T3 maps, not T2.
  
  ------

  Developed by NeverSink

  [![Follow me on Twitter](https://img.shields.io/badge/twitter-grey.svg?style=for-the-badge&logo=twitter)](https://twitter.com/NeverSinkDev) [![FilterBlade Discord](https://img.shields.io/badge/discord-grey.svg?style=for-the-badge&logo=discord)](https://discord.gg/mye6xhF) [![Watch FB Dev on Twitch](https://img.shields.io/badge/twitch-grey.svg?style=for-the-badge&logo=twitch)](https://twitch.tv/neversink) [![Support development on Patreon](https://img.shields.io/badge/patreon-grey.svg?style=for-the-badge&logo=patreon)](https://www.patreon.com/Neversink)
