template: |
  *All updates are also available through [FilterBlade](https://www.filterblade.xyz) and on the [PoE filter ladder](https://www.pathofexile.com/item-filter/ladder/follower). Major thanks to all patreon supporters to help us fund the continuous development. [Patreon](https://www.patreon.com/Neversink) supporters also receive a Patreon-exclusive [Filter-Auto-Updater](https://youtu.be/i8RJx0s0zsA).*
  
  ## SHORT OVERVIEW
  Valdo's Puzzle Box is now part of the T1 tier. Affects both stable and economy. This is the stable version for this league, unless something major will need changes. All of the tiering and thresholds adjustments have been highly succesful. I found the tiering this league to be very accurate and I hope you did too. I'll be keeping a close eye on the economy and will adjust the thresholds if needed.
  
  ## CHANGES
  - All tiers have been adjusted to the current economy
  - Added Valdo's Puzzle Box to T1 (were never hidden, but now have appropriate tiers, instead of 'pink unknown item color')
  - Added tiering to new uniques/divination cards (were never hidden, but now have appropriate tiers, instead of 'pink unknown item color')
  - Disabled the random 28%+ quality rule by default (except for flasks) as it no longer holds any real value
  
  ------

  Developed by NeverSink

  [![Follow me on Twitter](https://img.shields.io/badge/twitter-grey.svg?style=for-the-badge&logo=twitter)](https://twitter.com/NeverSinkDev) [![FilterBlade Discord](https://img.shields.io/badge/discord-grey.svg?style=for-the-badge&logo=discord)](https://discord.gg/mye6xhF) [![Watch FB Dev on Twitch](https://img.shields.io/badge/twitch-grey.svg?style=for-the-badge&logo=twitch)](https://twitch.tv/neversink) [![Support development on Patreon](https://img.shields.io/badge/patreon-grey.svg?style=for-the-badge&logo=patreon)](https://www.patreon.com/Neversink)
