template: |
  *All updates are also available through [FilterBlade](https://www.filterblade.xyz) and on the [PoE filter ladder](https://www.pathofexile.com/item-filter/ladder/follower). Major thanks to all patreon supporters to help us fund the continuous development. [Patreon](https://www.patreon.com/Neversink) supporters also receive a Patreon-exclusive [Filter-Auto-Updater](https://youtu.be/i8RJx0s0zsA).*
  
  ## SHORT OVERVIEW
  Added new tattoos into the tierlist. I intentionally did NOT do any tiering changes to the stable version. Economy-updated versions of course are retiered.
  
  ## TIERING ADJUSTMENTS:
  - 6 New tattoos added (these were NOT hidden in the old filter, but were not tiered)
  - The tierlists have NOT been adjusted on the stable filter. This is intentional. The economy-updated versions are retiered. In the future goal is to limit re-tiering processes on the stable filter to 2 per league (1 at release and 1 during first eco-update). This is experimental.
  
  ## MISC CHANGES:
  - Synthesised unique rings are now highlight by basetype, instead of class
  - Flasks are now consistently highlighted via class, instead of basetype
  
  ------

  Developed by NeverSink

  [![Follow me on Twitter](https://img.shields.io/badge/twitter-grey.svg?style=for-the-badge&logo=twitter)](https://twitter.com/NeverSinkDev) [![FilterBlade Discord](https://img.shields.io/badge/discord-grey.svg?style=for-the-badge&logo=discord)](https://discord.gg/mye6xhF) [![Watch FB Dev on Twitch](https://img.shields.io/badge/twitch-grey.svg?style=for-the-badge&logo=twitch)](https://twitch.tv/neversink) [![Support development on Patreon](https://img.shields.io/badge/patreon-grey.svg?style=for-the-badge&logo=patreon)](https://www.patreon.com/Neversink)
