template: |
  *All updates are also available through [FilterBlade](https://www.filterblade.xyz) and on the [PoE filter ladder](https://www.pathofexile.com/item-filter/ladder/follower). Major thanks to all patreon supporters to help us fund the continuous development. [Patreon](https://www.patreon.com/Neversink) supporters also receive a Patreon-exclusive [Filter-Auto-Updater](https://youtu.be/i8RJx0s0zsA).*
  
  ## SHORT OVERVIEW:
  
  I wanted to address a large number of small issues and QOL improvements in this update.
  
  ## NEW FEATURES
  - Leveling gem rules now require arealevel of 2+ in order to exclude them from popping up in kingsmarch inventories.
  - The rule for gems you receive at level 1, now requires the gems to have 0 quality and gem level 1. Additionally it requires the gem to be one of the active and support gems that can drop in twilight strand. This minimizes chances of them appearing in kingsmarch rewards.
  - Removed corrundum flask from most utility flask lists.
  - Normalized overquality rule treatment: pretty much any best basetype of 21%+ quality will not be hidden on any strictness now (tinctures, flasks, weapons, armors). This may show some items that are not worth much.
  - Reduced the tiering of scouting reports in the stable version. Economy based versions should be tiered based on the economy correctly already.
  - Added a new rule to highlight ILVL85 tinctures (disabled on uber-plus-strict)
  - Gave explorer scouting reports an extra bonk, since they were still overtiered
  - Increased the itemlevel offsets for generic rare items in the leveling section to prevent inconsistencies that could result in boss-drop rares being unintentionally hidden a few levels to early (this will likely receive a rework in the upcoming league). Thanks to CDR for pointing out the issue.
  
  ------

  Developed by NeverSink

  [![Follow me on Twitter](https://img.shields.io/badge/twitter-grey.svg?style=for-the-badge&logo=twitter)](https://twitter.com/NeverSinkDev) [![FilterBlade Discord](https://img.shields.io/badge/discord-grey.svg?style=for-the-badge&logo=discord)](https://discord.gg/mye6xhF) [![Watch FB Dev on Twitch](https://img.shields.io/badge/twitch-grey.svg?style=for-the-badge&logo=twitch)](https://twitch.tv/neversink) [![Support development on Patreon](https://img.shields.io/badge/patreon-grey.svg?style=for-the-badge&logo=patreon)](https://www.patreon.com/Neversink)
