template: |
  *All updates are also available through [FilterBlade](https://www.filterblade.xyz) and on the [PoE filter ladder](https://www.pathofexile.com/item-filter/ladder/follower). Major thanks to all patreon supporters to help us fund the continuous development. [Patreon](https://www.patreon.com/Neversink) supporters also receive a Patreon-exclusive [Filter-Auto-Updater](https://youtu.be/i8RJx0s0zsA).*
  
  - Further improved the tiering of many items and added more safeguards
  - Added a new optional rule to hide corrupted + magic/normal zana maps
  - Added a rule for low tier zana maps
  - Added economy based tiering for runegrafts and allflames
  - Several filterblade specific improvements
  - Several smaller itemlevel changes
  - Improved the highlight of 6WhiteSocket weapons
  - Mercenary modded items have more highlight now
  - Adjusted several identified mod rules
  - The conditional hide rules that activate as you progess further in maps now only affect armors (caused confusion when working with rare weapons on filterblade on very-strict)
  - Low quality flasks now have more priority than some other early endgame flask rules
  - Small gold piles are no longer shown on uberstrict and up
  
  ------

  Developed by NeverSink

  [![Follow me on Twitter](https://img.shields.io/badge/twitter-grey.svg?style=for-the-badge&logo=twitter)](https://twitter.com/NeverSinkDev) [![FilterBlade Discord](https://img.shields.io/badge/discord-grey.svg?style=for-the-badge&logo=discord)](https://discord.gg/mye6xhF) [![Watch FB Dev on Twitch](https://img.shields.io/badge/twitch-grey.svg?style=for-the-badge&logo=twitch)](https://twitch.tv/neversink) [![Support development on Patreon](https://img.shields.io/badge/patreon-grey.svg?style=for-the-badge&logo=patreon)](https://www.patreon.com/Neversink)
