template: |
  *All updates are also available through [FilterBlade](https://www.filterblade.xyz) and on the [PoE filter ladder](https://www.pathofexile.com/item-filter/ladder/follower). Major thanks to all patreon supporters to help us fund the continuous development. [Patreon](https://www.patreon.com/Neversink) supporters also receive a Patreon-exclusive [Filter-Auto-Updater](https://youtu.be/i8RJx0s0zsA).*
  
  This version focuses on improving the tiering of allflames and polishing. It affects stable as well, but only the allflame tiering is changed!
  
  ## NECROPOLIS CHANGES:
  
  - Reviewed the tiering of allflames
  
  ## MISC CHANGES AND BUG FIXES:
  
  - The new corrupted jewel section now correctly highlights all magic 1-corrupted-mod jewels.
  - Added the flask class to high level life/mana flasks to prevent some niche bugs on filterblade
  - Added deicide mask to the T1 perfection based items.
  - Added full dragonscale to the T1 perfection based items
  
  ------

  Developed by NeverSink

  [![Follow me on Twitter](https://img.shields.io/badge/twitter-grey.svg?style=for-the-badge&logo=twitter)](https://twitter.com/NeverSinkDev) [![FilterBlade Discord](https://img.shields.io/badge/discord-grey.svg?style=for-the-badge&logo=discord)](https://discord.gg/mye6xhF) [![Watch FB Dev on Twitch](https://img.shields.io/badge/twitch-grey.svg?style=for-the-badge&logo=twitch)](https://twitch.tv/neversink) [![Support development on Patreon](https://img.shields.io/badge/patreon-grey.svg?style=for-the-badge&logo=patreon)](https://www.patreon.com/Neversink)
