template: |
  *All updates are also available through [FilterBlade](https://www.filterblade.xyz) and on the [PoE filter ladder](https://www.pathofexile.com/item-filter/ladder/follower). Major thanks to all patreon supporters to help us fund the continuous development. [Patreon](https://www.patreon.com/Neversink) supporters also receive a Patreon-exclusive [Filter-Auto-Updater](https://youtu.be/i8RJx0s0zsA).*
  
  ## SHORT OVERVIEW:
  
  This update adds much requested uniques-for-disenchanting-rules to the filter! These are disabled by default, but can be enabled on filterblade. This update further improves strictness balance, basetype tiering etc.
  
  ## NEW FEATURES
  - Added 3 new OPTIONAL rules (can be enabled on FilterBlade): Unique items that are worth 5000+/2500+/1250+ dust-per-inventory slot. The content of these rules has been originally compiled by S1D3WYZ, I modified it further and added some additional bases. These are entirely separate and are not part of the unqiue tierlist and placed in a way that it will never override T1, T2 and valuable mutlibase drops.
  
  ## BASETYPES
  - The expensive bases rule can now contain the new endgame armors, not just old atlas bases.
  - Added a new rule to highlight high perfection new bases.
  
  ## TIERING
  - Omen tiering has been improved
  - Omen now have 5 tiers instead of 4.
  - Made scarab rules strictness slighlty less strict
  - T4 currency divination cards are now hidden on uber-plus strict instead of uber-strict
  
  ## MISC
  - Corrupted abyss jewels have now more priority (hiding ilvl 86 jewels will no longer hide corrupted ones)
  
  ------

  Developed by NeverSink

  [![Follow me on Twitter](https://img.shields.io/badge/twitter-grey.svg?style=for-the-badge&logo=twitter)](https://twitter.com/NeverSinkDev) [![FilterBlade Discord](https://img.shields.io/badge/discord-grey.svg?style=for-the-badge&logo=discord)](https://discord.gg/mye6xhF) [![Watch FB Dev on Twitch](https://img.shields.io/badge/twitch-grey.svg?style=for-the-badge&logo=twitch)](https://twitch.tv/neversink) [![Support development on Patreon](https://img.shields.io/badge/patreon-grey.svg?style=for-the-badge&logo=patreon)](https://www.patreon.com/Neversink)
