template: |
  *All updates are also available through [FilterBlade](https://www.filterblade.xyz) and on the [PoE filter ladder](https://www.pathofexile.com/item-filter/ladder/follower). Major thanks to all patreon supporters to help us fund the continuous development. [Patreon](https://www.patreon.com/Neversink) supporters also receive a Patreon-exclusive [Filter-Auto-Updater](https://youtu.be/i8RJx0s0zsA).*
  
  ## SHORT OVERVIEW
  Talamoana exile. This patch adds support for all that new and old trial of the ancestor items. Additionally it features large scale improvements to tiering, fractured items, influenced items, cluster jewels, jewels, gems, divination cards, uniques, currency and much more. It also features a bunch of architecture improvements and quite a few FilterBlade features.
  
  We hope you'll enjoy the new league and the new filter!
  
  ## TRIAL OF THE ANCESTOR CHANGES:
  - Added a tierlist for all the tattoos (with safety section in case some were missed)
  - Added a tierlist for all the omen (with safety section in case some were missed)
  - Added a new rule for silver coins. They'll likely wander into the currency tierlist if trial goes core.
  - Added a new rule for hinekor's locks. They'll likely wander into the currency tierlist if trial goes core.
  - Added a rule to highlight forbidden tomes and related sanctum items
  - Wiped the dust of the sanctum relic rules
  
  ## TIERING ADJUSTMENTS:
  - All tierlists have been adjusted based on the current economy:
  - This currently includes the following tierlists: Uniques, Divination Cards, Fragments (incl. splinters), Currency (incl. stacked currency and shards), Scarabs, Unique Maps, Fossils, Incubators, Oils, Vials, Delirium Orbs, Invitations, Influenced Items, Expensive Atlas Bases, Cluster Jewels, Breachstones, Replicas and Gems.
  - Removed orbs that never drop in stacks or where the chance of an orb dropping in a stack is astronomically low from the 'stacked currency' section. These orbs are still highlighted in the 'currency' section.
  
  > *NeverSink's notes: I'm aware that stacked currency tiering on filterblade is currently in a bad spot, we're looking for a good UI to improve that situation. We're looking for good UI/UX suggestions for that. If you have any, please approach us on our discord!*
  
  - Anchored Exalted Orbs and Elevated Sextants to the T2 currency tier. This is to prevent economy anomalies early on in the league and them sometimes shifting to T1.
  - Delayed until next patch, it was giving us too many technical difficulties with existing filterblade savestates: ~~Moved ritual and crescent splinters into their own category out of currency~~
  - Removed the atlas base status from some atlas bases that are not used at all
  - Expanded the selection of 'good' eater/exarch bases with the focus on gloves and boots, especially ones that can roll suppression. All other ones are hidden on semi-strict and up.
  
  > *NeverSink's notes: In the future I'll likely rework the algorithm alltogether. That being said, I still count for influenced items to get reworked evenutally, with them barely seeing any use compared to fractured/eldritch bases, with some very few niche exceptions, such as some boots, helmets and gloves (usually elevated/awakened ultra-endgame bases). Maybe the atlas expansion will change them.*
  
  ## INFLUENCED ITEMS:
  
  > *NeverSink's notes: Influenced basetype tiering has been frustrating to handle based on economy data alone. The main reasons are that there's a huge variety of basetype-itemlevel-influence-cost combinations. This results in weird items entering the economy. Additionally crafted item, chancing bases and people misspricing made the economy-data frustrating to handle.*
  >
  > *This is a bit of a move of desperation and I already have a better system planned, but I'm done playing idiot-whack-a-mole and I hope so are you. I'm introducing a double blacklist in the economy tiering. The 'T1' blacklist forbids a base to ever enter T1 or T2 of the influenced tierlist. 'T2' items will receive a major cut to their 'confidence' value when tiering. The blacklist is mostly used on super low level bases.*
  >
  > *I will closely monitor the situation*
  
  - Influenced item tiering now employ a two-tier-black-list to prevent pointless items from entering the economy tiering.
  - The general influenced item tiering algorithm has been improved
  
  ## FRACTURED ITEMS:
  
  > *NeverSink's notes: Fractured items are some of the most important crafting bases in the game. Previously I've been using a 3-tier approach, where the first tier is filtering by specific bases, the second tier by class and the third tier everything else. This approach had a bunch of issues, such as making filterblade editing complicated and also merging armor-types. For instance when the second tier was highlighting ALL fractured gloves, it'd also highlight low level fractured ES gloves, which are significantly less useful than the low-evasion based gloves, which can roll suppression.*
  >
  > *To improve the tiering, I'm adding a second basetype-based tier. This allows for a lot more precision and gives filterblade users more capabilities as well. I'm keeping the class-based tier around for exotic items, such as fractured heist bases, maps etc.*
  >
  > *Below you'll find the logic employed when adjusting the tiers*
  
  - Reviewed all T1 and T2 fractured bases. They have all been retiered
  - Generally: gear that can roll suppression has more bases highlighted
  - Generally: energy shield and armor bases require higher basetypes to be highlighted
  - Generally: most boots are highlighted, but T1 focuses on the better bases
  - Generally: many helmets/gloves are highlighted, but T1 focuses on the better bases
  - Generally: all rings, belts and amulets are highlighted among the T1/T2 bases
  - Nearly all one handed fractured caster weapons are highlighted among the T1 and T2 tier. T1 tier focuses on the bases with the better implicits
  - Most attack weapons are only shown if they're one of the best/meta bases (with the exception of some best T2 maces, axes, claws and some others). - A lot of bows and quivers are highlighted as well. T1 focuses on the better bases as usual.
  
  ## REMOVED SECTIONS:
  - Crucible crafting section has been removed
  - Crucible currency section has been removed
  
  ## STYLE IMPROVEMENTS:
  - Items that previously had a black background (0 0 0) now have a SLIGHTLY non-black one (20 20 0). In practice the game renders things still EXACTLY 100% black, probably due to some postprocessing uniqueness in POEs implementation. However, when hovering/selecting the item it will receive a distinct slightly-golden background! This makes looting slightly easier as it's easier to spot the hovered item! This effect is being applied as a post-processing layer during filter generation and is not part of the filter files/style files. If this looks weird or off to you please let me know. I'm especially interested in console/macOS feedback as I don't know how their rendering works
  
  ## STRICTNESS ADJUSTMENTS:
  
  > *NeverSink's notes: I'm treating atlas bases more and more like other base, as they've been losing their position to fractured/eldritch and synthesized bases. The changes to the strictness here are a preparation for a larger full scale rarity/endgame crafting base items rework.*
  
  - Increased the strictness on the filtering of 'perfection-bases' (itemlevel 86 armours with perfect base defense multiplier)
  - Increased the strictness of atlas base filtering. Random normal atlas bases below itemlevel 86 are now hidden in the endgame on strict and above. You'll still stumble across occasional rare bases.
  - T3 fractured items are now hidden on strict instead of very strict
  
  > *NeverSink's notes: Over the years, I've been adding a lot of different special cases for jewels, as both jewel types have had their mod-pool expanded several times. The goal now is to give them a consistent and clear treatment: very strict removes pretty much all*
  
  - Revamped the strictness of generic and abyss jewel rules
  - Generic Jewels: Magic jewels are hidden on strict (68+)
  - Generic Jewels: Magic jewels ILVL 1-68 are hidden on very strict
  - Generic Jewels: Rare jewels are hidden on uber strict
  - Abyss Jewels: Magic jewels ILVL1-68 are hidden on very strict (for leveling)
  - Abyss Jewels: Magic jewels ILVL68-81 are hidden on strict
  - Abyss Jewels: Magic jewels ILVL86+ are hidden on uber-plus-strict
  - Abyss Jewels: Rare jewels ILVL1-85 are hidden on uber strict
  - Abyss Jewels: Rare jewels 86+ are hidden on uber-plus-strict
  - The filter now highlights any ILVL84 12 node large cluster jewel (until uber-plus-strict) independent of the economy data
  - Not new, but important for next changes: The filter now highlights any ILVL84 8 node large cluster jewel (until uber-plus-strict) independent of the economy data
  - 8-Node Large Cluster jewels that were NOT matched by economy data are hidden on uber-strict
  - Random Large Cluster jewels are hidden on very strict
  - Random Medium Cluster jewels are now hidden on very strict
  - Random Small Cluster jewels are now hidden on very strict
  
  ## LEVELING ADJUSTMENTS:
  
  > *NeverSink's notes: I noticed some minor inconsistencies during the very early levels of the campaign. This should help it feel better by unifying highlights and sizes*
  
  - Magic items until level 9 have now slightly higher font size than before
  - Small chromatic (RGB) items while leveling now have  higher font size
  - Wands and sceptres have been added to the list of early-items (until level 9) that receive extra highlight when 3 sockets. Previously this list only included gloves, shields, boots and helmets.
  - Until level 9 all random non-tiny magic items have a slightly stronger border
  
  ## IDENTIFIED MOD FILTERING:
  - Many identified mod filtering rules now also filter for 'negative mods'. For instnace identified boots rules will not highlight boots anymore with 4 good mods, but low tier movement speed. Similary an identified physical damage weapon, won't be highlighted if it has a very low tier flat phys mods, even if it has other good mods (this has been already part of 8.10.5, but now also affects the stable branch)
  
  ## FILTERBLADE:
  - This filter supports adds further support to a major FilterBlade's best advanced features - custom rules! We've added and expanded support for duplicating, reording, renaming rules and much more. This was one of our major goals for the next league, but with ExileCon and Diablo4 being on the horizon, we've decided to prioritize our FilterBlade dev sprint and release earlier
  - FilterBlade tierlist
  
  ## MISC CHANGES:
  
  - Removed engraved ultimatum rule as it was made completely redundant by the unique map tierlist
  - Added new gems into the +1 recipe sections
  - Expanded a lot of check for the item to be uncorrupted with a unmirror check as well.
  - Removed "Infused Engineer's Orb" as it doesn't drop anymore
  - Removed some outdated no-longer-dropping incubators from the tierlists
  - Endgame low strictness quality flasks are now only highlighted when normal
  - Added a sectino to highlight stacked scarabs
  - Lots of other minor adjustments
  
  ## ARCHITECTURE IMPROVEMENTS:
  > *NeverSink's notes: In the coming monthes and year we'll be doing a lot of architecture/infrastructre adjustments to support 3 filters (poe1,poe2,mobile or more!) in the future, it's a major part of our roadmap now, but we believe the improvements will allow for a whole number of general benefits as well!*
  
  - Improved the structure of the 'aspect' files that are used to economy-tier the filters
  - Reworked the 'Waypoint' system within the filter. This system enables FilterBlade to use a ton of different locations for custom rules that are forward compatible with future filter update versions.
  - Further improvements to filter structure and generation
  
  ------

  Developed by NeverSink

  [![Follow me on Twitter](https://img.shields.io/badge/twitter-grey.svg?style=for-the-badge&logo=twitter)](https://twitter.com/NeverSinkDev) [![FilterBlade Discord](https://img.shields.io/badge/discord-grey.svg?style=for-the-badge&logo=discord)](https://discord.gg/mye6xhF) [![Watch FB Dev on Twitch](https://img.shields.io/badge/twitch-grey.svg?style=for-the-badge&logo=twitch)](https://twitch.tv/neversink) [![Support development on Patreon](https://img.shields.io/badge/patreon-grey.svg?style=for-the-badge&logo=patreon)](https://www.patreon.com/Neversink)
