template: |
  *All updates are also available through [FilterBlade](https://www.filterblade.xyz) and on the [PoE filter ladder](https://www.pathofexile.com/item-filter/ladder/follower). Major thanks to all patreon supporters to help us fund the continuous development. [Patreon](https://www.patreon.com/Neversink) supporters also receive a Patreon-exclusive [Filter-Auto-Updater](https://youtu.be/i8RJx0s0zsA).*
  
  ## SHORT OVERVIEW
  All the crucible content has been added! Importantly: we added a new section that is specifically there to highlight some white/magic items in the endgame to have some food for the crucible forge/krangler. Currently this section contains generally good bases or bases that share a good unique (for the chance of a unique sell node). The current list is: "Convoking Wand" "Champion Kite Shield" "Spine Bow" "Imperial Claw" "Opal Sceptre" "Prophecy Wand" "Short Bow" "Siege Axe". You can customize it on FilterBlade. This rule is disabled on Very strict.
  
  This patch contains MAJOR tiering improvements to unique, divination card and other tiering types and a TON of other changes (check the patch notes for more info). It also contains major improvements to the FilterBlade UI and FilterBlade meta data!
  
  Good luck in the crucible league!
  
  ## NEW LEAGUE ITEMS
  - Added the new crucible currencies
  - Added a section to highlight items (rare or lower) with crucible trees (these should not drop by default, but I've learned that things tend to change over time, so it's good to be on the safe side)
  - Added a section to highlight items (unique) with crucible trees (these should not drop by default, but I've learned that things tend to change over time, so it's good to be on the safe side)
  - Added new divination cards
  - Added a new section that is specifically there to highlight some white/magic items in the endgame to have some food for the crucible forge/krangler. Currently this section contains generally good bases or bases that share a good unique (for the chance of a unique sell node). The current list is: "Convoking Wand" "Champion Kite Shield" "Spine Bow" "Imperial Claw" "Opal Sceptre" "Prophecy Wand" "Short Bow" "Siege Axe". You can cusotmize it on FilterBlade. This rule is disabled on Very strict.
  - Added special tiering to new uniques
  
  ## MAJOR FILTERBLADE IMPROVEMENTS
  - Tierlists hover-information is vastly improved. It contains additional data, filters out relics and is much more concise.
  - Tierlists now can show extra-data about a certain item or a specific unique. This is for instance used to visualize where a certain unique drops, the rewards of incubators etc. Also it just looks really rad.
  - Reworked all hover-UIs on FilterBlade. These are much more concise and useful now
  
  ## LEAGUE RELATED ADJUSTMENTS
  - Added a section to detect maps with 'implicit' mods that can drop under some circumstances (like the shadow shaping node)
  - Removed the 'of Unwavering' abyss jewel ID detection mod
  - Removed 'Serpent Wand' that was causing issues with the new patch for some reason
  - Renamed 'The Iron Bard' divination card
  - Moved breachstones to it's own tierlist
  
  ## MAP LIKE ITEM CHANGES
  - Disabled the section for detecting nemesis+beyond maps as this combo no longer has any value after the last 2 leagues
  
  ## UNIQUE TIERING
  - Made a ton of adjustments to the unique tiering aspects (meta-information).
  - Reviewed and adjusted the tiering strategy for a lot of uniques. This includes over 50 aspect changes and will improve tiering in many cases!
  - Removed a bunch of aspects from no-longer-dropping uniques. This will lead to a bunch of uniques that were previously landing in the "non-drop-category" to land into the hideable category
  - Cleaned up and added special exceptions to handle no longer dropping basetypes and race rewards better.
  - A huge thank you to @mellontoss for compiling tons of data and suggestions for the unique changes!
  - Added an exception to highlight starforge/voidforge drops based on their influence! Note that we can't recommend disabling unique infernal sword drops as Echoforge can't be detected.
  - Revamped the algorithm to be slightly more exclusive when it comes to 'semi-expensive' and 'multi-base' uniques. Items found in this section should be significantly better than the hidable uniques on average.
  - Improved the 'early league unique tiering'. Cleaned up the list of early league uniques to be a bit more strict.
  - Marked most abyss and most breach items as 'buffed'. They'll be tiered slightly better than their previous tiering was in the last league and are not allowed to enter the 'hideable' uniques during the first days of the league.
  - Marked all sanctum items as 'non-drop'
  - Slightly increased the divine price component of the price requirement for T1 uniques
  - Slightly increased the price requirement for multibase uniques
  - Slightly increased the price scaling for semi-expensive uniques
  
  ## DIVINATION CARD ALGORITHM
  - I scrapped the old algorithm and rewrote it from scratch. Divination card tiering data coming from the economy is still dirtier than the infinite hunger fight, but the new algorthm seems be performing much better overall.
  - Cleaned and improved the aspects (meta-information) of the divination cards. This should lead to some improved tiering in some niche cases.
  - The Lingering Remnants Divination card is no longer allowed to drop below T4
  
  ## UNIQUE JEWEL TIERING
  - [DISABLED, feature will be readded soon] Added minimal unique jewel tiering where possible. In the case of most jewels this does not work as too many jewels share the same base. However, some jewels such as abyss jewels are now economy-tiered.
  - Rational doctrine drops are now highlighted as T1 (using the fact that they're the only synthesised jewel)
  - Megalomaniac jewel moved to T2 from multibase
  
  ## OTHER TIERING CHANGES
  - Standardized and clean up all tiering algorithms. This should lead to a more consistent tiering in the future.
  - Breachstones and splinters have received some temporary adjustments to improve their tiering in regards to the 3.21 changes
  - Further improved cluster jewel tiering. The tiering algorithm is now more reluctant to put cluster jewels into the T1 category during the early league (as the data is super hazy)
  
  ## MISC CHANGES
  - Added a new section on FilterBlade (and a disabled by default rule in the filter) that highlights quality minion gems for +1 helmet recipes!
  - Added 3.21 and 3.20 gems to the +1 recipe highlight sections
  - Increased the stack size requirement on all simulacrum splinters to create high tier sounds/highlights.
  - Removed a bunch of unique map bases that no longer drop
  - Removed lures from the fragment tab as these no longer drop ingame.
  - Added new abyss mods to the identified abyss jewel section
  
  ------

  Developed by NeverSink

  [![Follow me on Twitter](https://img.shields.io/badge/twitter-grey.svg?style=for-the-badge&logo=twitter)](https://twitter.com/NeverSinkDev) [![FilterBlade Discord](https://img.shields.io/badge/discord-grey.svg?style=for-the-badge&logo=discord)](https://discord.gg/mye6xhF) [![Watch FB Dev on Twitch](https://img.shields.io/badge/twitch-grey.svg?style=for-the-badge&logo=twitch)](https://twitch.tv/neversink) [![Support development on Patreon](https://img.shields.io/badge/patreon-grey.svg?style=for-the-badge&logo=patreon)](https://www.patreon.com/Neversink)
