template: |
  *All updates are also available through [FilterBlade](https://www.filterblade.xyz) and on the [PoE filter ladder](https://www.pathofexile.com/item-filter/ladder/follower). Major thanks to all patreon supporters to help us fund the continuous development. [Patreon](https://www.patreon.com/Neversink) supporters also receive a Patreon-exclusive [Filter-Auto-Updater](https://youtu.be/i8RJx0s0zsA).*
  
  This update focuses on improving tiering for all the new items, improves the strictness handling of certain rares and does some fixes here and there.
  
  This is the stable tiering/economy version for this league. The stable filters will preserve their tiering for the rest of the league.
  
  ## SHORT OVERVIEW:
  
  - Retiered all items (uniques, currency, divination cards etc)
  - Fixed an issue where 'of Infamy' normal mods and merc mods shared the same name resulting in weapons with attack speed being highlighted way too hard (ggg probably forgot that they already used the mod name?). Added a new section for infamy weapons.
  - Made mod-based veiled highlight a lot less strong and is treated like a normal veiled mod (except for elreon). You can enable specific highlights on filterblade.
  - Done a lot of fixes and improvements to the tiering safeguards. The system has proven itself to be very powerful and useful so far.
  - Added tiering for runegrafts
  - Added tiering for allflames
  - Adjusted strictnesses for veiled items
  
  ------

  Developed by NeverSink

  [![Follow me on Twitter](https://img.shields.io/badge/twitter-grey.svg?style=for-the-badge&logo=twitter)](https://twitter.com/NeverSinkDev) [![FilterBlade Discord](https://img.shields.io/badge/discord-grey.svg?style=for-the-badge&logo=discord)](https://discord.gg/mye6xhF) [![Watch FB Dev on Twitch](https://img.shields.io/badge/twitch-grey.svg?style=for-the-badge&logo=twitch)](https://twitch.tv/neversink) [![Support development on Patreon](https://img.shields.io/badge/patreon-grey.svg?style=for-the-badge&logo=patreon)](https://www.patreon.com/Neversink)
